name: hello-world-Git-Action
on: push
jobs:
 push-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-PUSH-step1
        run: echo "*********PUSH Step--1--Hello World!********"
      - name: my-PUSH-step2
        run: echo "********PUSH Step--2--Hello World!-22222********"
      - name: my-PUSH-step4
        run: echo "********PUSH Step--4--Hello World!-********"
      - name: my-PUSH-step3
        run: echo "********PUSH Step--3--Hello World!********"
 
 pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: my-PULL-step2
        run: echo "STEP2...######## PULL:Hello World!#########"
      - name: my-PULL-step1
        run: echo "STEP1...######## PULL:Hello World!#########"
      - name: my-PULL-step3
        run: echo "STEP3...######## PULL:Hello World!#########"
