## Working all events 09 March -- Action--This Line is Added in -- 19::03::::In Branch1-04Branch
name: hello-world-Git-Action
'on': 
  pull_request:
  push:
jobs:
  DEV:
     runs-on: ubuntu-latest
     environment: DEV
  push-job:
        runs-on: ubuntu-latest
        steps:
          - name: Run a Script==> Push Job
            run: echo "PUSH ==> I AM RUNNING IN **DEV** ENVIRONMENT *****"
  pull_request:
        runs-on: ubuntu-latest
        steps:
          - name: Run a Script==> Pull Job
            run: echo "Action - pull_request"
  merged:
       if: github.event.pull_request.merged == false
       runs-on: ubuntu-latest
       steps:
        - name: Run a Script==> Merged Job
          run: echo "Merge Failed!!!"
  create-pull-request:
        runs-on: ubuntu-latest
        steps:      
           - name: my-PULL-step2
             run: echo "ACTION ::== create-pull-request"
  build-on-merge:
        if: startsWith(github.event.head_commit.message, 'Merge pull request')
        runs-on: ubuntu-latest
        steps:
         - name: my-PULL-step2
           run: echo "Action ::= build-on-merge!!!build-on-merge"
  merge-me:
        name: Merge me!
        runs-on: ubuntu-latest
        steps:
         - name: MergeEventToMain
           run: echo "Action ::= merge-me!!!"
  QA:
    runs-on: ubuntu-latest
    environment: DEV
    push-job:
       runs-on: ubuntu-latest
       steps:
          - name: Run a Script==> Push Job
            run: echo "PUSH ==> I AM RUNNING IN **DEV** ENVIRONMENT *****"
    pull_request:
        runs-on: ubuntu-latest
        steps:
        - name: Run a Script==> Pull Job
          run: echo "Action - pull_request"
          merged:
          if: github.event.pull_request.merged == false
           runs-on ubuntu-latest
          steps:
           - name Run a Script==> Merged Job
             run echo "Merge Failed!!!"
    create-pull-request:
            runs-on: ubuntu-latest
            steps:      
            - name: my-PULL-step2
            run: echo "ACTION ::== create-pull-request"
            build-on-merge:
            if: startsWith(github.event.head_commit.message, 'Merge pull request')
              runs-on:ubuntu-latest
    steps:
        runs-on: ubuntu-latest
        steps:
        - push-job:
        - name: my-PULL-step2
          run: echo "Action ::= build-on-merge!!!build-on-merge"
              merge-me:
          - name: Merge me!
             runs-on ubuntu-latest
            steps:
            - name: MergeEventToMain
            run: echo "Action ::= merge-me!!!"
