name: hello-world-Git-Action
on: 
  pull_request:
    branches: [Branch1_04March]
    types: [closed]
  push:
   branches:
      - main
      - develop
jobs:
 push-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-PUSH-step1
        run: echo "*********PUSH to Step--1--Hello World!********Updated Branch 01 Text"
      - name: my-PUSH-step2
        run: echo "********PUSH Step--2--Hello World!-22222********Updated Branch 02 Text"
      - name: my-PUSH-step4
        run: echo "********PUSH Step--4--Hello World!-********"
      - name: my-PUSH-step3
        run: echo "********PUSH Step--3--Hello World!********"
 pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: my-PULL-step2
        run: echo "STEP2...######## PULL:Hello World!#########"
      - name: my-PULL-step1
        run: echo "STEP1...######## PULL:Hello World!#########"
      - name: my-PULL-step3
        run: echo "STEP3...######## PULL:Hello World!#########"
 merged:
  if: github.event.pull_request.merged == true
  runs-on: ubuntu-latest
  steps:
    - name: MergeEventToMain
      run: echo "Merged_Action1:!!Merge Failed!!!"
 if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Merged Action2:::!!!Git_Merged::The PR was merged!!!!
