name: WorkFlowTest1_4March
on: push
jobs:
 push-job:
    runs-on: ubuntu-latest
    steps:
      - name: WorkFlowTest1_4March==> Name ONE
        run: echo "PUSH:::WorkFlowTest1_4March==> Name ONE"
      - name: WorkFlowTest1_4March==> Name TWO
        run: echo "PUSH:::WorkFlowTest1_4March==> Name TWO"
      - name: WorkFlowTest1_4March==> Name THREE
        run: echo "PUSH:::WorkFlowTest1_4March==> Name THREE"
      - name: WorkFlowTest1_4March==> Name FOUR
        run: echo "PUSH:::WorkFlowTest1_4March==> Name FOUR"
 
 pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: my-PULL-step2
        run: echo "PULL:::STEP1...######## PULL:Hello World!#########"
      - name: my-PULL-step1
        run: echo "PULL:::STEP2...######## PULL:Hello World!#########"
      - name: my-PULL-step3
        run: echo "PULL:::STEP3...######## PULL:Hello World!#########"
